Update FastCD.yml

diff --git a/.github/workflows/FastCD.yml b/.github/workflows/FastCD.yml
--- a/.github/workflows/FastCD.yml
+++ b/.github/workflows/FastCD.yml
@@ -1,4 +1,4 @@
-name: CD
+name: FastCD
 
 on:
   workflow_dispatch:
@@ -39,15 +39,16 @@ jobs:
 
       - name: Determine version
         run: |
-          case "${{ inputs.version }}" in
-            "major"|"minor"|"patch")
-              npm version "${{ inputs.version }}"
-              ;;
-            *)
-              echo "Invalid version input. Please use 'major,' 'minor,' or 'patch'."
-              exit 1
-              ;;
-          esac
+          if [ "${{ inputs.version }}" == "major" ]; then
+            npm version major
+          elif [ "${{ inputs.version }}" == "minor" ]; then
+            npm version minor
+          elif [ "${{ inputs.version }}" == "patch" ]; then
+            npm version patch
+          else
+            echo "Invalid version input. Please use 'major,' 'minor,' or 'patch'."
+            exit 1
+          fi
 
       - name: Push changes
         run: git push --follow-tags
